### ISSUE TITLE
No release versions for Davin since alpha12?

### ISSUE THREAD

**Issue by ralfr** [iota-tangle-io/dtlg#13]
Is there any reason you‘re now longer offering binary releases for Darwin since alpha12++?
—-

**Comment by luca-moser** [comment]
Travis CI pipeline fails for whatever reason on the darwin build, will fix it in the near future.

**Comment by luca-moser** [comment]
Please check the latest release: https://github.com/iota-tangle-io/dtlg/releases/download/alpha16/dtlg-alpha16-mac64.zip (I don't have mac so I can't verify whether it works but linux/win builds are fine)
