### ISSUE TITLE
Issues with node selection

### ISSUE THREAD

**Issue by PatriQ94** [iota-tangle-io/dtlg#4]
Node does not switch properly upon entering it

**Comment by Jimbob-Iota** [comment]
Seems you have to start spamming and then change the node and hit enter while it's running.

**Comment by luca-moser** [comment]
Fixed in alpha4. Note that because of concurrency, the console might output a TX from the last node while the spammer started with the new node. Therefore check whether the next TX really was not made via the specified new node.
