### ISSUE TITLE
After crash theres zero notifications

### ISSUE THREAD

**Issue by PatriQ94** [iota-tangle-io/dtlg#5]
A guy tried running another spammer simultaneously, the dtlg spammer stopped working, no error, nothing in logs, just stopped...

**Comment by luca-moser** [comment]
Can't reproduce without more details. By the way, obviously only one spammer instance can be run on the same machine simultaneously, as the app uses port 9090 per default and running multiple DTLGs would lead them to not be able to listen on the same port.
