### ISSUE TITLE
Add "Choose TAG" as a textbox beside "Choose node"

### ISSUE THREAD

**Issue by PatriQ94** [iota-tangle-io/dtlg#6]

**Comment by cyclux** [comment]
Thought about this aswell, but isn't it better to hard code the TAG to keep track of the spammers? Or will all spammers continue to use `PIIBSWTXHZYQZYGRXWQFVILKMU9JPIIYXS9NRKHBJPPEJSBJVKGMINOIRCVWNLDHUZDWALCJBTOTTOFBTCPEZUQHUB` as the address to keep track?

**Comment by cyclux** [comment]
Either the address or the TAG, at least one of both should be hardcoded to identify it as SPAMALOT spammer for analytic purposes.

**Comment by luca-moser** [comment]
DTLG will now automatically use a tag in the following schema: "999DTLG9" + OS + "9" + POW_TYPE
